### ISSUE TITLE
Can't reopen modal after closing.

### ISSUE THREAD

**Issue by studio404pl** [benceg/vanilla-modal#34]
If i will trigger action:
```modal.open('#form_modal_wrap');```
it appears, after that i want to close it:
```modal.close('#form_modal_wrap');```
it's gone.. now how can i reopen it again? After executing:
```modal.open('#form_modal_wrap');```
i am getting error: 
```VanillaModal: VanillaModal target must exist on page.```

**Comment by justincasey** [comment]
I can confirm this same issue.

**Comment by studio404pl** [comment]
@justincasey thank you for hint. After removing few transitions from css that were applied to modal elements it started to work. Strange that this bug was related to css animations.

**Comment by olegburakov** [comment]
I wraped `modal.open` method by `setTimout` function:

` modal.close(); 
    setTimeout(function () { // open another one
      modal.open('#thank-you-modal');
    }, 350)`

delay must be bigger than transition duration
