### ISSUE TITLE
modal.open() trigger an error

### ISSUE THREAD

**Issue by francois2metz** [benceg/vanilla-modal#41]
Hi,

Calling `modal.open('#selector')` trigger an error `TypeError: node is null`.

Here is a testcase: https://jsfiddle.net/zv51yj57/

**Comment by benceg** [comment]
@francois2metz, in your JSFiddle, you've given your modal `id="modal-content-1"` but you're calling `vanillaModal.open('#modal-contant-1')`. Modal works as expected if the target has the same ID as the argument passed to the `open` method.
